### ISSUE TITLE
Option: use Click to implement command line interface

### ISSUE THREAD

**Issue by AlexanderSenf** [JULIETYCL/DRS_client#4]
There are many ways to implement a command line interface (CLI) in Python. One of them is using `argparse`, which is standard Python3. But there are also other libraries that make certain aspects of writing CLIs better (although that depends on personal preference in some cases). 

It is a good exercise to take a working CLI and re-create it using `click`. This is used in many places, so knowledge of how to program with it is beneficial.

So, this issue is for re-implementing the CLI using `click`.

https://click.palletsprojects.com/en/8.1.x/
https://www.assemblyai.com/blog/the-definitive-guide-to-python-click/

**Comment by JULIETYCL** [comment]
Done

**Comment by AlexanderSenf** [comment]
The next step is to upload the development branch to GitHub, and issue a pull request. That way it will be possible to review the code changes before they are merged to the main branch.

**Comment by JULIETYCL** [comment]
Thanks. I have completed it.

**Comment by AlexanderSenf** [comment]
Let me know when the Pull Request is ready, I will review it

**Comment by JULIETYCL** [comment]
Hi Alexander. Pull request is ready.

**Comment by AlexanderSenf** [comment]
Thank you; although I can't actually see it yet in https://github.com/JULIETYCL/DRS_client/pulls

**Comment by JULIETYCL** [comment]
Please do the following : The main page of the repo -> pull requests -> new pull requests -> development       From: Alexander SenfSent: Sunday, May 21, 2023 7:19 AMTo: JULIETYCL/DRS_clientCc: JULIETYCL; CommentSubject: Re: [JULIETYCL/DRS_client] Option: use Click to implement command line interface (Issue #4) Thank you; although I can't actually see it yet in https://github.com/JULIETYCL/DRS_client/pulls—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

**Comment by JULIETYCL** [comment]
Please do the following :
 
The main page of the repo -> pull requests -> new pull requests -> development

**Comment by AlexanderSenf** [comment]
Thank you; this is a potential pull request, and I can see the commits you have made; could you please create the actual pull request from it? then I will be able to review and comment on it,
